name: Java CI

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Cache Gradle packages and wrapper
      uses: actions/cache@v2.1.4
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
        restore-keys: ${{ runner.os }}-gradle-
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - uses: gradle/wrapper-validation-action@v1
    - name: Build with Gradle
      run: ./gradlew build --info --stacktrace --warning-mode summary
    - name: Publish Test Report
      uses: scacap/action-surefire-report@v1
      if: ${{ always() && github.event.pull_request.head.repo.full_name == github.repository && github.actor != 'dependabot[bot]' }}
      with:
        report_paths: '**/build/test-results/*/TEST-*.xml'
        github_token: ${{ secrets.GITHUB_TOKEN }}
    - name: Sonar analysis
      if: ${{ env.SONAR_TOKEN != null }}
      run: |
        ./gradlew sonarqube -Dsonar.host.url=https://sonarcloud.io \
                            -Dsonar.organization=kaklakariada-github \
                            -Dsonar.login=$SONAR_TOKEN \
                            --info --stacktrace --warning-mode=summary
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    - name: Archive portmapper binary
      uses: actions/upload-artifact@v2
      with:
        name: portmapper
        path: build/libs/portmapper-*-all.jar
